### ISSUE TITLE
Error with tukui (not elvui)

### ISSUE THREAD

**Issue by antsy8** [AndreWaehlisch/More-Stopwatches#1]
Seems to not allow me to create new timers with tukui enabled but will work if I disable, create timers, then reenable my UI

**Comment by AndreWaehlisch** [comment]
I am not a user of Tukui, but I think the newest version on Curse should work for you. Please test it.

https://github.com/AndreWaehlisch/More-Stopwatches/commit/80c9454f3592830c9919b0b00e49b2a82d7496d7

**Comment by antsy8** [comment]
Perfect! Thank you!
