### ISSUE TITLE
attempt to call global 'IsAddOnLoaded' (a nil value)

### ISSUE THREAD

**Issue by calummitchell** [AndreWaehlisch/More-Stopwatches#2]
3x ...rfaceMoreStopwatches/MoreStopwatchesCore.lua:420: attempt to call global 'IsAddOnLoaded' (a nil value)
[string "@MoreStopwatches/MoreStopwatchesCore.lua"]:420: in function <...rfaceMoreStopwatches/MoreStopwatchesCore.lua:44>

Locals:
self = Frame {
}
event = "ADDON_LOADED"
addonName = "MoreStopwatches"
paramsPrototype = <table> {
}
pattern = <table> {
 number = "^(%d+%.?%d*)%s+(.*)$"
 string = "^(%S*)%s*(.-)$"
}
MoreStopwatchesString = "MoreStopwatches: "
(*temporary) = nil
(*temporary) = "Blizzard_TimeManager"
(*temporary) = "attempt to call global 'IsAddOnLoaded' (a nil value)"

Replace IsAddOnLoaded() with C_AddOns.IsAddOnLoaded()

**Comment by AndreWaehlisch** [comment]
I don't have a subscription right now, so I can only test with a trial account. Nevertheless, it seems to work for me with the update I just pushed (v1.30). Let me know if you encounter any more bugs.

**Comment by calummitchell** [comment]
Fixed, thanks!
